# Generated by Django 4.2.4 on 2023-09-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_properties_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
    ]
