# Generated by Django 4.2.4 on 2023-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_properties_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='name',
        ),
        migrations.AddField(
            model_name='properties',
            name='addr',
            field=models.TextField(null=True),
        ),
    ]
