# Generated by Django 4.2.4 on 2023-10-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_properties_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='detail',
        ),
    ]
