# Generated by Django 4.2.4 on 2023-10-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_remove_electronics_detail_remove_furniture_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='image1',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image2',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='cars',
            name='image1',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='cars',
            name='image2',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='image1',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='image2',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image1',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image2',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image1',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image2',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
    ]
