# Generated by Django 4.2.4 on 2023-10-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_bikes_image1_bikes_image2_cars_image1_cars_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
